pipeline {
    agent any

    tools {
        jdk 'jdk17'
        nodejs 'node20'
    }

    environment {
        IMAGE_NAME = 'bharathm746/react-todo'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                script {
                    echo "Cleaning workspace..."
                    deleteDir() // Removes old files
                }
            }
        }

        stage('Git Checkout') {
            steps {
                script {
                    git branch: 'main',
                        credentialsId: 'github_seccred',
                        url: 'https://github.com/bharathmurugan/Devops-MiniProject'
                }
            }
        }

        stage('Install Dependencies & Build') {
            steps {
                script {
                    sh '''
                    cd task-manager
                    
                    if [ -f package.json ]; then
                        echo "package.json found. Running npm install..."
                        npm install
                        npm run build
                    else
                        echo "ERROR: package.json is missing in task-manager!"
                        exit 1
                    fi
                    '''
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker_hub', toolName: 'docker') {
                        sh """
                        cd task-manager
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }

        stage('Deploy Docker Container') {
            steps {
                script {
                    sh """
                    docker stop react_todo_container || true
                    docker rm react_todo_container || true
                    docker run -d --name react_todo_container -p 8080:80 ${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }
    }
}

